### PR TITLE
fix: update refreshTokenQueryParamName from 'refreshToken' to 'code'

### PR DESCRIPTION
**Pull request by totzk9**
Issue link: https://github.com/nhost/nhost-dart/issues/111

### CODE REVIEW

**Comment by mhadaily** [comment]
mm, I am not sure about this, checking at `https://github.com/nhost/nhost/tree/1b7dcf2121f6de7a439437464719a40a50abe69e/packages/hasura-auth-js` it looks like it is still `refreshToken` I mean Hasura auth should return you this at the end.

**Comment by totzk9** [comment]
Yeah kinda weird that OAuth would return `code` instead of `refreshToken`. Might also depends on which provider.
Also btw, the returned `code` from facebook provider actually fails to verify. I've reported this to discord https://discord.com/channels/552499021260914688/1026377069304758334/threads/1144642504935874630

**Comment by totzk9** [comment]
I tried the google oauth and it also returns `code` instead of `refreshToken`

**Comment by dbarrosop** [comment]
I am closing this PR as I think the premise of the issue is incorrect (see #111). But feel free to reopen otherwise.

**Pull request closed without merging**
