### PR TITLE
feat(nhost-storage): added image transform options to getPresignedUrl

### PR DESCRIPTION
**Pull request by PhilippS93**
Hi, 
nhost storage added in https://github.com/nhost/hasura-storage/releases/tag/v0.3.4 the capability to add transform parameters to the presigned url.
I included these in the request.

### CODE REVIEW

**Review by totzk9 — CHANGES_REQUESTED** [review]

**Review by mhadaily — APPROVED** [review]
LGTM, waiting for CI and will merge and release afterwards

**Comment by mhadaily** [comment]
Can you make sure this "Check for broken links / link-check" check is fixed?

**Comment by PhilippS93** [comment]
> Can you make sure this "Check for broken links / link-check" check is fixed?

I have synced the fork. The logs for the checks were already expired.

**Review by mhadaily — APPROVED** [review]
LGTM

**Review by mhadaily — APPROVED** [review]
LGTM, thanks you

**Pull request merged**
